import os
import csv
import json
import bcrypt
from flask import Flask, render_template, request, jsonify, session, redirect, url_for, send_from_directory
from werkzeug.security import generate_password_hash, check_password_hash
from models import db, Admin, Candidate, Test, TestAttempt, AuditLog
from datetime import datetime

app = Flask(__name__)
app.secret_key = 'railway_cbt_secure_production_key'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///railway_cbt.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)

# --- HELPER: AUDIT LOGGING ---
def log_audit(user_id, user_type, action, details, ip_address):
    log = AuditLog(user_id=user_id, user_type=user_type, action=action, details=details, ip_address=ip_address)
    db.session.add(log)
    db.session.commit()

# ==========================================
# PWA (PROGRESSIVE WEB APP) ROUTES
# ==========================================
@app.route('/manifest.json')
def manifest():
    return send_from_directory('static', 'manifest.json', mimetype='application/json')

@app.route('/service-worker.js')
def service_worker():
    return send_from_directory('static', 'service-worker.js', mimetype='application/javascript')

# ==========================================
# AUTHENTICATION ROUTES
# ==========================================
@app.route('/')
def index():
    return redirect(url_for('candidate_login'))

@app.route('/candidate/login', methods=['GET', 'POST'])
def candidate_login():
    if request.method == 'POST':
        lobby_id = request.form.get('lobby_id')
        name = request.form.get('candidate_name')
        phone = request.form.get('phone')
        post = request.form.get('post')
        
        candidate = Candidate.query.filter_by(lobby_id=lobby_id, candidate_name=name, phone=phone, post=post).first()
        
        if candidate:
            session['candidate_id'] = candidate.id
            session['candidate_name'] = candidate.candidate_name
            session['lobby_id'] = candidate.lobby_id
            session['zone'] = candidate.zone
            session['post'] = candidate.post
            log_audit(candidate.id, 'candidate', 'Candidate Login', f"Lobby ID: {lobby_id}", request.remote_addr)
            return redirect(url_for('test_selection'))
        return render_template('candidate_login.html', error="Invalid Details. Ensure exact match.")
    return render_template('candidate_login.html')

@app.route('/admin/login', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        admin = Admin.query.filter_by(username=username, status='active').first()
        
        if admin:
            is_valid = False
            stored_hash = admin.password
            
            # --- THE PHP TO PYTHON PASSWORD TRANSLATOR ---
            if stored_hash.startswith('$2y$'):
                # Python's bcrypt expects $2a$ or $2b$. We safely swap the PHP $2y$ prefix.
                compatible_hash = stored_hash.replace('$2y$', '$2a$').encode('utf-8')
                try:
                    is_valid = bcrypt.checkpw(password.encode('utf-8'), compatible_hash)
                except Exception as e:
                    print(f"Bcrypt error: {e}")
            else:
                # Handle new passwords generated by Python/Werkzeug
                try:
                    is_valid = check_password_hash(stored_hash, password)
                except ValueError:
                    is_valid = False
            
            if is_valid:
                session['admin_id'] = admin.id
                session['admin_name'] = admin.full_name
                session['admin_type'] = admin.user_type
                session['zone'] = admin.zone
                session['division'] = admin.division
                session['lobby'] = admin.lobby
                
                admin.last_login = datetime.utcnow()
                db.session.commit()
                log_audit(admin.id, admin.user_type, 'Admin Login', 'Successful', request.remote_addr)
                return redirect(url_for('admin_dashboard'))
                
        return render_template('admin_login.html', error="Invalid Credentials")
    return render_template('admin_login.html')

@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('candidate_login'))

# ==========================================
# ADMIN DASHBOARD & REGISTRATION
# ==========================================
@app.route('/admin/dashboard')
def admin_dashboard():
    if 'admin_id' not in session: 
        return redirect(url_for('admin_login'))
    return render_template('admin_dashboard.html')

@app.route('/admin/register_candidate', methods=['GET', 'POST'])
def register_candidate():
    if 'admin_id' not in session:
        return redirect(url_for('admin_login'))
        
    admin_type = session.get('admin_type')
    admin = Admin.query.get(session['admin_id'])
    
    if request.method == 'POST':
        # --- THE 5-TIER HIERARCHY LOGIC ---
        if admin_type == 'superadmin':
            zone = request.form.get('zone')
            division = request.form.get('division')
            lobby = request.form.get('lobby')
        elif admin_type == 'zonal_superadmin':
            zone = admin.zone
            division = request.form.get('division')
            lobby = request.form.get('lobby')
        elif admin_type == 'division_admin':
            zone = admin.zone
            division = admin.division
            lobby = request.form.get('lobby')
        else:
            zone = admin.zone
            division = admin.division
            lobby = admin.lobby

        new_candidate = Candidate(
            lobby_id=request.form.get('lobby_id'),
            candidate_name=request.form.get('candidate_name'),
            zone=zone,
            division=division,
            lobby=lobby,
            post=request.form.get('post'),
            email=request.form.get('email'),
            phone=request.form.get('phone'),
            created_by=admin.id
        )
        
        try:
            db.session.add(new_candidate)
            db.session.commit()
            log_audit(admin.id, admin_type, 'Register Candidate', f"Assigned to {zone}/{division}/{lobby}", request.remote_addr)
            return render_template('register_candidate.html', success=f"Candidate Registered to {zone}/{division}/{lobby}!")
        except Exception as e:
            db.session.rollback()
            return render_template('register_candidate.html', error="Error: Lobby ID already exists.")
            
    return render_template('register_candidate.html')

# ==========================================
# ADVANCED ADMIN MANAGEMENT ROUTES
# ==========================================
@app.route('/admin/manage_admins', methods=['GET', 'POST'])
def manage_admins():
    if 'admin_id' not in session or session.get('admin_type') not in ['superadmin', 'zonal_superadmin']:
        return redirect(url_for('admin_dashboard'))
        
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        hashed_pw = generate_password_hash(password) 
        
        user_type = request.form.get('user_type')
        if session.get('admin_type') == 'zonal_superadmin' and user_type in ['superadmin', 'zonal_superadmin']:
            return render_template('manage_admins.html', error="You cannot create admins of equal or higher rank.")
            
        new_admin = Admin(
            username=username,
            password=hashed_pw,
            full_name=request.form.get('full_name'),
            email=request.form.get('email'),
            zone=request.form.get('zone', session.get('zone')),
            division=request.form.get('division', 'ALL'),
            lobby=request.form.get('lobby', 'ALL'),
            user_type=user_type,
            created_by=session['admin_id']
        )
        db.session.add(new_admin)
        db.session.commit()
        return redirect(url_for('manage_admins'))
        
    if session.get('admin_type') == 'superadmin':
        admins = Admin.query.all()
    else:
        admins = Admin.query.filter_by(zone=session.get('zone')).all()
        
    return render_template('manage_admins.html', admins=admins)

@app.route('/admin/view_candidates')
def view_candidates():
    if 'admin_id' not in session: return redirect(url_for('admin_login'))
    
    admin_type = session.get('admin_type')
    if admin_type == 'superadmin':
        candidates = Candidate.query.all()
    elif admin_type == 'zonal_superadmin':
        candidates = Candidate.query.filter_by(zone=session.get('zone')).all()
    elif admin_type == 'division_admin':
        candidates = Candidate.query.filter_by(division=session.get('division')).all()
    else:
        candidates = Candidate.query.filter_by(lobby=session.get('lobby')).all()
        
    return render_template('view_candidates.html', candidates=candidates)

@app.route('/admin/view_results')
def view_results():
    if 'admin_id' not in session: return redirect(url_for('admin_login'))
    
    query = db.session.query(TestAttempt, Candidate, Test)\
        .join(Candidate, TestAttempt.candidate_id == Candidate.id)\
        .join(Test, TestAttempt.test_id == Test.id)
        
    admin_type = session.get('admin_type')
    if admin_type != 'superadmin':
        if admin_type == 'zonal_superadmin':
            query = query.filter(Candidate.zone == session.get('zone'))
        elif admin_type == 'division_admin':
            query = query.filter(Candidate.division == session.get('division'))
        else:
            query = query.filter(Candidate.lobby == session.get('lobby'))
            
    results = query.order_by(TestAttempt.attempt_date.desc()).all()
    return render_template('view_results.html', results=results)

@app.route('/admin/test_management', methods=['GET', 'POST'])
def test_management():
    if 'admin_id' not in session or session.get('admin_type') not in ['superadmin', 'zonal_superadmin']:
        return redirect(url_for('admin_dashboard'))
        
    if request.method == 'POST':
        test_id = request.form.get('test_id')
        test = Test.query.get(test_id)
        if test:
            test.test_name = request.form.get('test_name')
            test.max_score = float(request.form.get('max_score'))
            test.passing_percentage = float(request.form.get('passing_percentage'))
            test.time_limit = int(request.form.get('time_limit'))
            test.status = request.form.get('status')
            test.test_description = request.form.get('test_description')
            db.session.commit()
            return redirect(url_for('test_management'))
            
    tests = Test.query.order_by(Test.test_number).all()
    return render_template('test_management.html', tests=tests)


# ==========================================
# CANDIDATE TEST ROUTES
# ==========================================
@app.route('/candidate/test_selection')
def test_selection():
    if 'candidate_id' not in session: 
        return redirect(url_for('candidate_login'))
    
    tests = Test.query.filter_by(status='active').order_by(Test.test_number).all()
    attempts = TestAttempt.query.filter_by(candidate_id=session['candidate_id']).all()
    attempted_tests = [a.test_id for a in attempts]
    
    completed_count = len(set(attempted_tests))
    total_tests = len(tests)
    progress_pct = (completed_count / total_tests * 100) if total_tests > 0 else 0
    all_completed = completed_count >= total_tests if total_tests > 0 else False
    
    return render_template('test_selection.html', 
                           tests=tests, 
                           attempted_tests=attempted_tests,
                           completed_count=completed_count,
                           total_tests=total_tests,
                           progress_pct=progress_pct,
                           all_completed=all_completed)

@app.route('/test_interface/<int:test_id>')
def test_interface(test_id):
    if 'candidate_id' not in session: return redirect(url_for('candidate_login'))
    
    test = Test.query.get_or_404(test_id)
    g13_questions, g13_error = [], ""
    
    if test.test_number == 13:
        csv_path = os.path.join(app.root_path, 'g13_questions.csv')
        try:
            with open(csv_path, mode='r', encoding='utf-8') as file:
                reader = csv.reader(file)
                next(reader, None) # Skip Header
                for row in reader:
                    if len(row) >= 6 and row[1].strip():
                        g13_questions.append({
                            'q': row[1].strip(),
                            'optA': row[2].strip() if len(row) > 2 else '',
                            'optB': row[3].strip() if len(row) > 3 else '',
                            'optC': row[4].strip() if len(row) > 4 else '',
                            'ans': row[5].strip().upper() if len(row) > 5 else 'A'
                        })
        except Exception as e:
            g13_error = f"Error reading CSV: {str(e)}"

    session['test_start_time'] = datetime.utcnow().timestamp()
    
    return render_template('test_interface.html', 
                           test=test, 
                           g13_data=json.dumps(g13_questions), 
                           g13_error=g13_error)

# ==========================================
# API: SAVE TEST RESULTS (ONLINE SYNC)
# ==========================================
@app.route('/api/save_test_result', methods=['POST'])
def save_test_result():
    if 'candidate_id' not in session: 
        return jsonify({'success': False, 'message': 'Not logged in'})
    
    data = request.get_json()
    start_time = session.get('test_start_time', datetime.utcnow().timestamp())
    time_taken = int(datetime.utcnow().timestamp() - start_time)
    result_status = 'pass' if data['passed'] else 'fail'
    
    new_attempt = TestAttempt(
        candidate_id=session['candidate_id'],
        lobby_id=session.get('lobby_id'),
        test_id=data['test_id'],
        score=data['score_obtained'],
        max_score=data['max_score'],
        percentage=data['percentage'],
        result=result_status,
        time_taken=time_taken
    )
    db.session.add(new_attempt)
    db.session.commit()
    
    candidate = Candidate.query.get(session['candidate_id'])
    if candidate.test_status == 'not_started':
        candidate.test_status = 'in_progress'
        db.session.commit()
    
    session.pop('test_start_time', None)
    return jsonify({'success': True, 'attempt_id': new_attempt.id})

# ==========================================
# INITIALIZATION & STARTUP
# ==========================================
def setup_database():
    with app.app_context():
        db.create_all()
        # Seed the first superadmin if the database is empty
        if not Admin.query.filter_by(username='admin').first():
            hashed_pw = generate_password_hash('password123')
            default_admin = Admin(
                username='admin', 
                password=hashed_pw, 
                full_name='Master System Admin', 
                user_type='superadmin',
                zone='ALL',
                division='ALL',
                lobby='ALL'
            )
            db.session.add(default_admin)
            db.session.commit()
            print("Default admin created! Username: 'admin', Password: 'password123'")

if __name__ == '__main__':
    setup_database()
    app.run(debug=True, port=5000)